version: '3.4'

services:
  bw.assessment.authentication.api:
    image: ${DOCKER_REGISTRY-}bwassessmentauthenticationapi
    build:
      context: .
      dockerfile: BW.Assessment.Authentication.Api/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:80;https://+:443
    - ASPNETCORE_HTTPS_PORT=7001 
    - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssword01
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
        - "7000:80"
        - "7001:443"
    volumes:
        - ~/.aspnet/https:/https:ro

  bw.assessment.wallet.api:
    image: ${DOCKER_REGISTRY-}bwassessmentwalletapi
    build:
      context: .
      dockerfile: BW.Assessment.Wallet.Api/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:80;https://+:443
    - ASPNETCORE_HTTPS_PORT=8001 
    - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssword01
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
        - "8000:80"
        - "8001:443"
    volumes:
        - ~/.aspnet/https:/https:ro

  bw.assessment.shop.api:
    image: ${DOCKER_REGISTRY-}bwassessmentshopapi
    build:
      context: .
      dockerfile: BW.Assessment.Shop.Api/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    - ASPNETCORE_URLS=http://+:80;https://+:443
    - ASPNETCORE_HTTPS_PORT=9001 
    - ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssword01
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    ports:
        - "9000:80"
        - "9001:443"
    volumes:
        - ~/.aspnet/https:/https:ro

